### ISSUE TITLE
data written to stdin is echoed on stdout

### ISSUE THREAD

**Issue by ryanbmilbourne** [Gottox/child_pty#10]
Given the sample code:
```
var child = pty.spawn('node', ['--interactive'])

child.stdout.on('data', function(data){
    console.log('stdout: '+data)
})

child.stdin.write('process.exit()\n')
```

I get the following output:
```
stdout: process.exit()

stdout: 
stdout: 
stdout: > 
stdout: p
stdout: r
stdout: o
stdout: ces
stdout: s
stdout: .
stdout: e
stdout: xi
stdout: t
stdout: (
stdout: )
stdout: 
```

Whereas with the same code using `child_process` instead of , I only see the prompt as stdout:
```
stdout: > 
```

It looks like stdin is being mirrored across the stdout stream.  Is that expected behavior for `child_pty`?

**Comment by Gottox** [comment]
That's an inherent behavior of a pty. You may disable echoing using `stty -echo`, but that won't work for node and most other interactive applications.
