### ISSUE TITLE
`console.log` in forked process uses `\r\n` as line terminator on OSX.

### ISSUE THREAD

**Issue by jamestalmage** [Gottox/child_pty#12]
If I use `child_pty` to fork an node executable, and the executable contains the following:

```js
#!/usr/bin/env node

console.log('foo');
```

It ends up printing:

```js
"foo\r\n"
```
to the piped stream, even on OSX, where it should be just `\n`.

**Comment by Gottox** [comment]
This is done by the pty ( = the kernel) itself. IIRC There is way to change this behavior. The function is prepared but not yet exposed in child_pty. I'll do that with the next release.

**Comment by Gottox** [comment]
The function is now in master:
```
child = child_pty.spawn("/bin/sh");
child.pty.setattr({ oflag:{ ONLCR: false } });
child.stdout.on('data', console.log)
child.stdin.write("echo ABC\nexit\n");
```

**Comment by Gottox** [comment]
Can you check if it works for you?
