### ISSUE TITLE
Child_pty-3.0.4: ctrl-c fails

### ISSUE THREAD

**Issue by Gottox** [Gottox/child_pty#19]
Not exactly sure what's going on. See for reference: https://github.com/zeit/hyperterm/pull/319

**Comment by wmaciel** [comment]
Backspace is also failing.

You can verify it failing on the node-webterm demo.

**Comment by Gottox** [comment]
@wmaciel which OS?

**Comment by wmaciel** [comment]
I ran it on an Ubuntu server and the client was a Windows 10 box.

**Comment by Gottox** [comment]
okay, I may have found a bug. There was a bug in node-termios, that prevented child_pty from setting any termios properties. In node-termios-0.1.1 this bug was fixed. Since that this error occured.

In the next version I'll remove the termios support completely. (It's still possible to set these properties using node-termios from the frontend application.)
