### ISSUE TITLE
`end` event emitted twice

### ISSUE THREAD

**Issue by jkuri** [Gottox/child_pty#21]
Hi @Gottox, first of all, thanks for this great lib.

When I write `exit` to console the `end` event is emitted twice. Is that intended behaviour?

**Comment by Gottox** [comment]
Can you provide a testcase that triggers this behavior?

**Comment by jkuri** [comment]
sure, here's my code;

```js
import * as cpty from 'child_pty';

export default class {
  constructor(term, events) {
    this.term = term;
    this.events = events;

    this.pty = cpty.spawn('login', ['-fp', 'jan'], {
      cols: 120,
      rows: 30
    });

    this.events.on('input', data => {
      this.pty.stdin.write(data);
    });

    this.events.on('resize', data => {
      this.pty.stdin.resize({
        columns: data.col,
        rows: data.row
      });
    });

    this.pty.stdout.on('data', data => {
      this.events.emit('output', data);
    });

    this.pty.stdout.on('end', (data) => {
        this.events.emit('end'); // this is emitted twice
    });
  }
}
```
I did made some workaround and the things are working for me, anyway just to let you know.

**Comment by Gottox** [comment]
thx. On which platforms does this happen? OS, version, arch?

**Comment by jkuri** [comment]
That seems to happen on OSX 10.11.6 x64, but I can also try on Linux if that info helps you.

**Comment by Gottox** [comment]
That would be great, I'm currently not on my dev box, so I'll test your
code later.

**Comment by jkuri** [comment]
cool, thanks! I can also help to set up Travis configuration for OSX if you'd like.

**Comment by Gottox** [comment]
I reduced this testcase to the following:

```javascript
var cpty = require('./index')

class Foo {
  constructor(term, events) {
    this.term = term;
    this.events = events;

    this.pty = cpty.spawn('/bin/sleep', ['2'], {
      cols: 120,
      rows: 30
    });

    this.pty.stdout.on('data', data => {
			console.log("data");
    });

    this.pty.stdout.on('end', (data) => {
			console.log("end");
    });
  }
}

new Foo();
```

The output is:
```
end
```

Cannot reproduce your issue with that code.

**Comment by jkuri** [comment]
Thanks for checking on this. Looks like something else wasn't right on my side. Closing as it's not reproducable.
