### ISSUE TITLE
Failed to install child_pty on MacOS 10.12.3

### ISSUE THREAD

**Issue by joeyzhao0113** [Gottox/child_pty#23]
When I tried to install child_pty on mac os I got below error. The node version is `v7.2.0`. 

> $ npm install child_pty
> ⸨░░░░░░░░░░░░░░░░░░⸩ ⠙ normalizeTree: sill install loadCurrentTree
> ⸨   ░░░░░░░░░░░░░░░⸩ ⠦ cloneCurrentTree: sill cloneCurrentTree Finishing
> ⸨    ░░░░░░░░░░░░░░⸩ ⠼ fetchMetadata: sill mapToRegistry uri https://registry.npmjs.org/nan
> ⸨             ░░░░░⸩ ⠼ extract:child_pty: sill doParallel extract 5
> 
> > termios@0.1.4 install /Users/joey/dev/nodejs/ptydemo/node_modules/termios
> > node-gyp rebuild
> 
>   CXX(target) Release/obj.target/termios/src/termios.o
> 
> 
> 
>   SOLINK_MODULE(target) Release/termios.node
> 
> > child_pty@3.0.6 install /Users/joey/dev/nodejs/ptydemo/node_modules/child_pty
> > node-gyp rebuild
> 
>   CXX(target) Release/obj.target/exechelper/src/exechelper.o
>   LINK(target) Release/exechelper
>   CXX(target) Release/obj.target/pty/src/pty.o
> ../src/pty.cpp:66:11: error: use of undeclared identifier 'ttyname'; did you mean 'ptsname'?
>                         (tty = ttyname(slave)) == NULL)
>                                ^~~~~~~
>                                ptsname
> /usr/include/stdlib.h:218:7: note: 'ptsname' declared here
> char    *ptsname(int);
>          ^
>

**Comment by Gottox** [comment]
Version of MacOS?

**Comment by joeyzhao0113** [comment]
I am using `10.12.3 (16D32)`.

**Comment by Gottox** [comment]
https://gist.github.com/ba7731200229425d2cbcd5c8fb4fe213 does this patch help?

**Comment by Gottox** [comment]
Fixed in v3.0.7

**Comment by joeyzhao0113** [comment]
It works great, thanks.
