### ISSUE TITLE
Is there a way to separate input and output on child_pty?

### ISSUE THREAD

**Issue by joeyzhao0113** [Gottox/child_pty#24]
I tried `child_pty` and found that each input is sent to output. How can I suppress the input? Or how I can separate input and output in `stdout.on('data', function()` method?

**Comment by Gottox** [comment]
you can use the option field to disable echo:

```
child_pty.spawn('/bin/sh', [], {
  lflag: { ECHO: false }
});
```

Note that many shells and curses programms echo typed characters back to stdout/stderr when they detect a PTY. In such cases there's no way to distinguish between echoed and printed characters.
