### ISSUE TITLE
Differences between nodejs spawn and child_pty's spawn

### ISSUE THREAD

**Issue by Naatan** [Gottox/child_pty#25]
Hi, I'm very interested in porting this to Mozilla to possibly use terminal.js within a mozilla environment. It would be tremendously useful if you could explain what the limitations were that you ran into with nodejs spawn that made you decide to roll your own. Could you give a brief overview?

Thank you!

**Comment by Gottox** [comment]
This project actually uses node.js spawn. child_pty provides a pty backend instead of using pipes. For more information read [this](https://en.wikipedia.org/wiki/Pseudoterminal)
