### ISSUE TITLE
node v8.10.0 error

### ISSUE THREAD

**Issue by ghost** [Gottox/child_pty#29]
Hello.
After a few months i ran one project of mine.
I'm using child_pty and i get 

> tasoss@devtrans:~/nodetest$ node a.js 
node[21184]: ../src/pipe_wrap.cc:131:static void node::PipeWrap::New(const v8::FunctionCallbackInfo<v8::Value>&): Assertion `args[0]->IsInt32()' failed.
 1: node::Abort() [node]
 2: 0x11e77db [node]
 3: node::PipeWrap::New(v8::FunctionCallbackInfo<v8::Value> const&) [node]
 4: v8::internal::FunctionCallbackArguments::Call(void (*)(v8::FunctionCallbackInfo<v8::Value> const&)) [node]
 5: 0xb7a2cf [node]
 6: v8::internal::Builtin_HandleApiCall(int, v8::internal::Object**, v8::internal::Isolate*) [node]
 7: 0x39bafe8042fd
Aborted (core dumped)

I don't know if it's related to https://github.com/nodejs/node/issues/12152
Is there any chance to correct it because i use child_pty on some major parts of my app.
Thanks!

**Comment by Gottox** [comment]
What's the content of a.js?

**Comment by Gottox** [comment]
Ah, can reproduce with the tests.

**Comment by ghost** [comment]
Hello and thx for replying!
The content is a test file

> var child_pty = require('child_pty');
var child = child_pty.spawn('/bin/sh', []);
child.stdout.on('resize', function() {
	console.log('New columns: ' + this.columns);
	console.log('New rows:    ' + this.rows);
}).pipe(process.stdout);
child.stdout.resize({ columns: 80, rows: 48 });
child.stdin.write('ls -l\n');
child.stdin.write('exit\n');

This is a sample that exists in README.
Waiting for some good news :)
Thanks!

**Comment by Gottox** [comment]
Fixed in the v3 branch. I'm waiting for travis and then release v3.0.8.

**Comment by Gottox** [comment]
There are some deprecation warnings during the tests, but I'll fix them later.

**Comment by Gottox** [comment]
fixed in v3.0.8

**Comment by ghost** [comment]
Thank you very much!!! Really!
ps: if you find some free time please correct those warning ,  i have seen them too.
