### ISSUE TITLE
Not all data packets are properly flushed to child's stdin

### ISSUE THREAD

**Issue by rauchg** [Gottox/child_pty#3]
At least on Mac OSX. Notice the behavior of `ls` here (have to press enter twice)
https://cloudup.com/c0EzEYzHhYb

**Comment by Gottox** [comment]
Tried to reproduce that on FreeBSD. No success. It seems that I have to use MacOS.

**Comment by Gottox** [comment]
Can you try to use the `unbuffer` command on the node.js test script? `unbuffer` is part of [expect](http://expect.sourceforge.net/)

```
unbuffer node testscript.js
```

**Comment by Gottox** [comment]
Now that pty.js supports io.js, can you cross check if this issue happens on pty.js too?

**Comment by rauchg** [comment]
Yep, happens to both. cc @indutny, I tested with iojs 1.6.2 as well

**Comment by Gottox** [comment]
Okay, I guess, it's an issue in node/io.js then.

**Comment by indutny** [comment]
I guess it should be fixed by https://github.com/libuv/libuv/commit/7005d29

**Comment by Gottox** [comment]
Closing this issue. Thanks for the fix!
