### ISSUE TITLE
child error events not being emitted?

### ISSUE THREAD

**Issue by ryanbmilbourne** [Gottox/child_pty#9]
When I spawn "definitelyverynotacommand" using `child_process`, the child emits the following error:
```
{ [Error: spawn verydefinitelynotacommand ENOENT]
  code: 'ENOENT',
  errno: 'ENOENT',
  syscall: 'spawn verydefinitelynotacommand',
  path: 'verydefinitelynotacommand' }
```

When I spawn the same with `child_pty`, the `data` event listener is triggered with the following output, but there is no `error` listener triggered:
```
execvp: No such file or directory
```

Are there plans to emit `error` events a la `child_process`?

**Comment by Gottox** [comment]
Yea, good idea, I'll add that.

**Comment by ryanbmilbourne** [comment]
:+1:

**Comment by Gottox** [comment]
Please recheck.

**Comment by ryanbmilbourne** [comment]
Ok, I'm getting an error now, but I'm also getting "2" from a data event.  

Code:
``` js
var pty = require('child_pty')
  , util = require('util')

var child = pty.spawn('verydefinitelynotacommand')

child.stdout.on('data', function(data){
    console.log('child data:\n%s', data)
})

child.on('error', function(err){
    console.log('child error:\n'+util.inspect(err))
})

child.on('exit', function(code, signal){
    console.log('child exit: code: %s\tsignal: %s', code, signal)
})
```

Output:
```
child exit: code: 1	signal: null
child data:
2

child error:
{ [Error: spawn verydefinitelynotacommand ENOENT]
  code: 'ENOENT',
  errno: 'ENOENT',
  syscall: 'spawn verydefinitelynotacommand',
  path: 'verydefinitelynotacommand' }
```

**Comment by Gottox** [comment]
Whoops, my mistake. That's fixed.

**Comment by Gottox** [comment]
* [ ] The exit event should only be thrown when the status channel is closed ( = the child has executed successfully)

**Comment by Gottox** [comment]
@ryanbmilbourne Please recheck if `master` solves your issue. I'll release 2.0 as soon as you're satisfied ;)

**Comment by ryanbmilbourne** [comment]
Hmm, it looks like we're having an exception thrown:

```
child error:
{ [Error: spawn verydefinitelynotacommand ENOENT]
  code: 'ENOENT',
  errno: 'ENOENT',
  syscall: 'spawn verydefinitelynotacommand',
  path: 'verydefinitelynotacommand',
  spawnargs: [] }
events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: shutdown ENOTCONN
    at exports._errnoException (util.js:746:11)
    at Socket.onSocketFinish (net.js:240:26)
    at Socket.emit (events.js:104:17)
    at finishMaybe (_stream_writable.js:484:14)
    at endWritable (_stream_writable.js:493:3)
    at Socket.Writable.end (_stream_writable.js:459:5)
    at Socket.end (net.js:415:31)
    at Socket.<anonymous> (/Users/rmilbourne/spectcl/node_modules/child_pty/lib/child_pty.js:74:17)
    at Socket.emit (events.js:107:17)
    at readableAddChunk (_stream_readable.js:163:16)
```

Same sample code as above.

---

> The exit event should only be thrown when the status channel is closed ( = the child has executed successfully)

I'm not so sure, as the return code of 1 is potentially useful.  That being said, your goal looks to be to emulate `child_process`'s behavior when possible, and `child_process` does not emit exit when the child cannot be spawned, so your behavior is more correct in that regard. :+1:

**Comment by ryanbmilbourne** [comment]
@Gottox I see the issue is closed; did you determine the root cause of the exception being thrown above?

**Comment by Gottox** [comment]
I missread that part. Can you provide the node version you're using?

**Comment by ryanbmilbourne** [comment]
v0.12.5

**Comment by Gottox** [comment]
Okay, should be fixed on master now.

**Comment by ryanbmilbourne** [comment]
Looks like we're good! :+1:

**Comment by ryanbmilbourne** [comment]
@Gottox Does v2.0.0 published on `npm` include the commit that fixed the exception?

**Comment by Gottox** [comment]
wait for 2.0.1
